import React from 'react'
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
const AboutPage = () => {
    return (
        <>
            <div>
                <p>This is the about us page</p>
            </div>
        </>
    )
}

export default AboutPage
